- hosts: loadbalancer
  roles:
    - { role: nginx_lb, when: (enable_nginx_lb | default(false)) and (load_balancer_is_required | default(false)) }
    - { role: apache_lb, when: enabled_apache_lb | default(false)) and (load_balancer_is_required | default(false)) }
