---
- name: Include dynamic variables
  hosts: all
  tasks:
    - include_vars: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- import_playbook: ../static-assignments/common.yml

- import_playbook: ../static-assignments/uat-webservers.yml

- name: Mysql Installation
  hosts: all
- import_playbook: ../static-assignments//mysql.yml

- name: Loadbalancers assignment
  hosts: all
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required